### ISSUE TITLE
Add Switchbot Curtain support

### ISSUE THREAD

**Issue by dshanske** [Danielhiversen/pySwitchbot#11]
https://github.com/OpenWonderLabs/python-host/commit/926a0990a2156da60a8c0f73423d7fd192769b38

Looks like the coding is in the manufacturers repo.

**Comment by Danielhiversen** [comment]
I do not have the Switchbot Curtain, so I am not going to add support for it.

**Comment by dshanske** [comment]
@Danielhiversen Understandable. How would you feel about a PR? I'm not much of a Python programmer, but I think I could handle this. I want to try to upstream it into Home Assistant, where I believe you are also the maintainer of the component.

**Comment by Danielhiversen** [comment]
A pr would be great 👍

**Comment by daenny** [comment]
https://github.com/Danielhiversen/pySwitchbot/pull/13 initial work is done here.

**Comment by moretea** [comment]
#13 is merged, so AFAIK this ticket can be closed.
