### ISSUE TITLE
Add WoCeilingPro

### ISSUE THREAD

**Issue by jurmarcus** [Danielhiversen/pySwitchbot#166]
Looks like WoCeilingPro should be added as a new device here. I have both he Add WoCeiling and WoCeilingPro Lights, and I could test this and add it but I am not sure what is the quickest way to get this up and running and I am using this plugin through home assistant VM.

https://github.com/Danielhiversen/pySwitchbot/blob/a804c7863b253dfe0b09bdca3cd724d21c201492/switchbot/const.py#L24

**Comment by bdraco** [comment]
I don't have a Pro, but if you only a PR to add support for it, I'm happy to review it

**Comment by jurmarcus** [comment]
so how that the new year has started, what is the best way to get a test env up and running for pyswitchbot? is it through some type of ha-core setup?

**Comment by bdraco** [comment]
https://developers.home-assistant.io/docs/development_index
