### ISSUE TITLE
[SwitchBot Lock Encryption Key] Getting Failed to Authenticate 

### ISSUE THREAD

**Issue by weitheng** [Danielhiversen/pySwitchbot#179]
Hi I am getting `Failed to Authenticate` when trying to extract the SwitchBot Lock encryption key. My SwitchBot account is created and logged in using Apple 3rd Party Account, could that be the reason, if so, is there any fix to allow extraction of encryption key using 3rd party account?

**Comment by bdraco** [comment]
The tools can only use switchbot accounts

**Comment by christi-g** [comment]
I have the same problem. I use the "sign in with apple" in the Switchbot app... 
Somebody knows how to convert the account in "normal" Switchbot account?

**Comment by KiraPC** [comment]
Is there no way to enable 3rd Party Account? I'm logged in with google but I need encryption keys.

**Comment by captshadab** [comment]
this is so inconvenient. does switchbot wants us to transfer all devices to new account. this is absolutely insane. i have 20 devices around
