### ISSUE TITLE
Curtain 3 - QuietDrift support

### ISSUE THREAD

**Issue by cermakjn** [Danielhiversen/pySwitchbot#222]
Would it be possible to add a support to open/close the Curtains in a QuietDrift mode? According to the app it should be a single flag to send the command with it?

**Comment by quenthal** [comment]
Yes, there are few 01's to be replaced with ff's, functions to open/close to be called to use quietdrift keys and creating entities and/or service calls for those. 

OPEN_KEYS = [
    f"{REQ_HEADER}{CURTAIN_COMMAND}010100",
    f"{REQ_HEADER}{CURTAIN_COMMAND}05ff00",
]
OPEN_KEYS_SLOW = [
    f"{REQ_HEADER}{CURTAIN_COMMAND}010100",
    f"{REQ_HEADER}{CURTAIN_COMMAND}050100",
]
CLOSE_KEYS = [
    f"{REQ_HEADER}{CURTAIN_COMMAND}010164",
    f"{REQ_HEADER}{CURTAIN_COMMAND}05ff64",
]
CLOSE_KEYS_SLOW = [
    f"{REQ_HEADER}{CURTAIN_COMMAND}010164",
    f"{REQ_HEADER}{CURTAIN_COMMAND}050164",
]

**Comment by Junkbite** [comment]
so is this just not going to be implemented?? we've know for a bit now what enables drift mode

**Comment by Michal4K** [comment]
You can implement it. I am sure bdraco will kindly accept your pull requests...
