### ISSUE TITLE
Meter Pro discovered as Light Strip

### ISSUE THREAD

**Issue by saeedesmaili** [Danielhiversen/pySwitchbot#264]
Following [a discussion](https://github.com/home-assistant/core/issues/128502#issuecomment-2481048695) on Home Assistant issues, I was recommended to raise an issue here. 

Although I'm using the latest version of Home Assistant (2024.11.2) which includes the SwitchBot Meter Pro device, my two Meter Pro devices are discovered as Light Strips (and it apparently is [an issue with pySwithbot](https://github.com/home-assistant/core/issues/128502#issuecomment-2481070640)).

Is there any details I can provide to troubleshoot this?

**Comment by bdraco** [comment]
Turn on active scans and delete this line https://github.com/Danielhiversen/pySwitchbot/blob/9bcf9c3f72a978aa65255128d40babd10a456ade/switchbot/adv_parser.py#L72
