### ISSUE TITLE
v0.18.10 - No unconfigured devices found.

### ISSUE THREAD

**Issue by 88fingerslukee** [Danielhiversen/pySwitchbot#85]
I had been using a manually edited version due to the errors addressed in v 0.14.1. I just went to do an upgrade of HA and 0.18.10 was installed. My curtains instantly stopped responding and now I can't add them back once removed.

I get the No unconfigured devices found error. There are no log entries.

Help please?!?

**Comment by bdraco** [comment]
Please open an issue in the HA issue queue.

Thanks 👍 

https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml
